# User Configuration for ${keyboard.name}

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse Emulation Behaviors
CONFIG_ZMK_POINTING=y

# Soft Off Behavior
CONFIG_ZMK_PM_SOFT_OFF=n

CONFIG_ZMK_DISPLAY=y
